name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

env:
  {%- if cookiecutter.docker_registry == "ghcr" -%}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  {%- elif cookiecutter.docker_registry == "quay.io" -%}
  QUAY_USER: ${{ secrets.QUAY_DMS_CONTAINER_REGISTRY_USER }}
  QUAY_PASSWORD: ${{ secrets.QUAY_CONTAINER_REGISTRY_PASSWORD }}
  QUAY_ORGANIZATION: your_organzatin
  QUAY_TEAM: your_team
  {%- endif -%}

{% raw %}
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to push version updates
      packages: write  # Required to push Docker images to GHCR
      checks: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Build and Test
      id: build-test
      uses: ./.github/actions/build-and-test
      with:
        version-bump: ${{ github.event.inputs.version_bump || 'patch' }}
        commit-changes: 'true'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Git Tag
      if: success()
      run: |
        git tag v${{ steps.build-test.outputs.version }}
        git push origin v${{ steps.build-test.outputs.version }}

    - name: Push Docker Images
      if: success()
      run: ./scripts/deploy-all.sh
{% endraw %}