name: Patch Image with SSL

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The Docker Tag to pull (e.g., 0.1.0)"
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4

      - name: Set Destination Image Name (Lowercase)
        run: |
          REPO_LOWER=$(echo "{% raw %}${{ github.repository }}{% endraw %}" | tr '[:upper:]' '[:lower:]')
          echo "DESTINATION_IMAGE=ghcr.io/$REPO_LOWER" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@a0d57b8e43b6ef1cca20559d68cec2227e63fccd # v3
        with:
          registry: ghcr.io
          username: "{% raw %}${{ github.actor }}{% endraw %}"
          password: "{% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}"

      - name: Inspect Original Image for User
        id: inspect
        run: |
          docker pull {{ cookiecutter.docker_image_name }}:{% raw %}${{ inputs.tag }}{% endraw %}

          # Extract the User config
          ORIGINAL_USER=$(docker inspect --format='{% raw %}{{.Config.User}}{% endraw %}' {{ cookiecutter.docker_image_name }}:{% raw %}${{ inputs.tag }}{% endraw %})

          # Default to root if the image doesn't specify a user
          if [ -z "$ORIGINAL_USER" ]; then
            ORIGINAL_USER="root"
          fi

          echo "Detected original user: $ORIGINAL_USER"
          echo "original_user=$ORIGINAL_USER" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@b66d8774c665b789105b440514f0c97e6f19b06f # v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "{% raw %}${{ env.DESTINATION_IMAGE }}{% endraw %}:{% raw %}${{ inputs.tag }}{% endraw %}"
          build-args: |
            TAG={% raw %}${{ inputs.tag }}{% endraw %}
            ORIGINAL_USER={% raw %}${{ steps.inspect.outputs.original_user }}{% endraw %}
