name: Test Build Without Deploy

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (for testing purposes only)'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop ]

env:
  BACKEND_IMAGE_NAME: {{ cookiecutter.backend_image_name }}
  FRONTEND_IMAGE_NAME: {{ cookiecutter.frontend_image_name }}

  {%- if cookiecutter.docker_registry == "ghcr" -%}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  {%- elif cookiecutter.docker_registry == "quay.io" -%}
  QUAY_USER: ${{ secrets.QUAY_DMS_CONTAINER_REGISTRY_USER }}
  QUAY_PASSWORD: ${{ secrets.QUAY_CONTAINER_REGISTRY_PASSWORD }}
  QUAY_ORGANIZATION: your_organzatin
  QUAY_TEAM: your_team
  {%- endif -%}
  

{% raw %}
jobs:
  test-build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read  # Only read permissions needed
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Build and Test (No Commit)
      id: build-test
      uses: ./.github/actions/build-and-test
      with:
        version-bump: ${{ github.event.inputs.version_bump || 'patch' }}
        commit-changes: 'false'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test Docker Build
      run: ./scripts/deploy-all.sh --dry-run

    - name: Generate Test Report
      if: always()
      run: |
        echo "=== Test Build Report ==="
        echo "Workflow: Test Build Without Deploy"
        echo "Trigger: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Version (test): ${{ steps.build-test.outputs.version }}"
        echo "Frontend changed: ${{ steps.build-test.outputs.frontend-changed }}"
        echo "Backend changed: ${{ steps.build-test.outputs.backend-changed }}"
        echo ""
        echo "Status:"
        echo "- ✓ Dependencies installed"
        echo "- ✓ Build preparation completed"
        echo "- ✓ Docker build validation performed"
        echo "- ✓ No changes committed"
        echo "- ✓ No images pushed to registry"
        echo ""
        echo "This workflow validates the build process without making any permanent changes."
        echo "=== End Test Build Report ==="
{% endraw %}